### ISSUE TITLE
TRACKER: Checklist for the POC

### ISSUE THREAD

**Issue by mroeschke** [twosigma/pandas#23]
Expand our `generalized_window.rst` proposal document as POC showcasing:

- [x] Performance parity of our rolling mean implementation (https://github.com/twosigma/pandas/issues/17)
- [x] `GroupbyIndexer` and/or `ExpandingIndexer` example
- [x] Performance of `rolling.apply`
